theme: jekyll-theme-minimal
title: Andy Rosenbaum (罗安迪)
description: I am a Senior Applied Scientist in Machine Learning and Artificial Intelligence with an M.A. in Computational Linguistics from Brandeis University. I previously worked at Amazon Alexa AI and AGI for 10 years. I enjoy classical music, kosher cooking, and ice hockey.
logo: "/images/andy_head_shot_new.jpg"
twitter:
  username: andyjrosenbaum
