theme: jekyll-theme-minimal
title: Andy Rosenbaum (罗安迪)
description: I am a Senior Applied Scientist in Artificial Intelligence, Machine Learning and Speech & Language Understanding with an M.A. in Computational Linguistics from Brandeis University. I previously worked at Amazon Alexa AI and AGI for 10 years. I enjoy music theory & composition, ice hockey, and kosher & vegetarian cooking.
logo: "/images/andy_head_shot_new.jpg"
twitter:
  username: andyjrosenbaum
