theme: jekyll-theme-minimal
title: Andy Rosenbaum (罗安迪)
description: I am a Machine Learning Scientist at Amazon Alexa AI, with an M.A. in Computational Linguistics from Brandeis University. I enjoy classical music, vegetarian cooking, and ice hockey.
logo: "/images/andy_head_shot_full_zoom.jpeg"
twitter:
  username: andyjrosenbaum
