theme: minima
title: Andy Rosenbaum (罗安迪)
description: I am a Machine Learning Scientist at Amazon Alexa AI. I enjoy classical music, vegetarian cooking, and ice hockey.
logo: "/images/andy_head_shot_full_zoom.jpeg"

minima:
  social_links:
    twitter: andyjrosenbaum
    linkedin: andyjrosenbaum
